# Lecturer's PostgreSQL setup. Run with:  mvn spring-boot:run -Dspring-boot.run.profiles=postgres
# Start DB first:
# docker run --name dev-postgres -e POSTGRES_PASSWORD=mysecretpassword -p5432:5432 -d postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
